#pragma once

#include <SDKDDKVer.h>
#include <exception>
#include <cassert>
#include <fstream>
#include <sstream>
#include <memory>
#include <vector>
#include <string>
#include <map>
#include <deque>
#include <queue>
#include <set>
#include <algorithm>
#include <objbase.h>
#include <cstdint>
#include <functional>
#include <chrono>